### ISSUE TITLE
Implement facebook login and logout api

### ISSUE THREAD

**Issue by litstrong** [litstrong/bope#10]

**Comment by litstrong** [comment]
http://stackoverflow.com/questions/30739352/django-rest-framework-token-authentication-logout?rq=1

**Comment by litstrong** [comment]
微信开放平台：
https://open.weixin.qq.com/cgi-bin/index?t=home/index&lang=zh_CN

**Comment by litstrong** [comment]
React Native微信SDK集成（iOS和Android）：
http://react-china.org/t/react-native-sdk-ios-android/3418/1

**Comment by litstrong** [comment]
Wechat login feature is not the default feature, and the bar of requesting is high:
![4 pic_hd](https://cloud.githubusercontent.com/assets/1745189/16752535/fc98c1f6-4796-11e6-90f6-8a521ae5b22d.jpg)

**Comment by litstrong** [comment]
Since 3rd party login should be similar, switch to implement facebook login and replace it in the future.

**Comment by litstrong** [comment]
facebook login:
https://developers.facebook.com/apps/985071078278968/fb-login/

**Comment by litstrong** [comment]
response: {"authResponse":{"accessToken":"EAANZC6ruzBzgBANz5fki1ZA2O2ZBvTG18r8BaXn4PZA5OXCNsyB6jjFEguIEZAzHHbnof1mhBxb47RLo3QnaxMuAzhhnUCVfUY2HVgb5ex7eHBNtv0b2VTaPaR1iI2gErpZA6gBvizxVuGXtiOxTbISSYwy1XjTZApREisHpXxBrQZDZD","userID":"251838415201979","expiresIn":5947,"signedRequest":"yfxFe4P0pmKT7lxnZ_CzQQuQiYJcS6PRIP5YD7LKAzs.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUJMbjVER2VFQ1ZlVVFuejBhcFhpMWpUQ255VXRwMlAyT0RndWlSZWJvekhWQmFUc3JobUMwZ1k3aVFTSUhZRko2UHBKLVg0TDZvYjROTktINEJqWFhscWRYekZTRGM4TENQaXFacWJwdlJVbTd4RzB1NTJlTm9lQ1pHTC1QeEstX25Eb093WW03YlZwRnNSbHdjMzhlQTVMNGJUcDZsSGFURkl5SXRHSjZsbF90ZE9Pd1NYRFdGWm1OR3o1WENfSUVuajV4MDB2R1A3T1BRMEVYanpWS3RPWHZWeTFuWTFKV3c3aXdCYzZxTXFjY0NhcXJWNExXTkpBT2N6bU11MDI1Ry1hZHpWX0xEeUZYVkhGRkUyNmlWVmdSbXp3M1Zuak5xeUt4cTc3aVpvQUFFdkg2VExqOFl4WXlGRy1Yd3h1cGxBTEFnQ1UxY3FUZ2daazkyakxGYyIsImlzc3VlZF9hdCI6MTQ2ODMwMDg1MywidXNlcl9pZCI6IjI1MTgzODQxNTIwMTk3OSJ9"},"status":"connected"}

**Comment by litstrong** [comment]
https://parse.com/tutorials/adding-third-party-authentication-to-your-web-app

**Comment by litstrong** [comment]
http://blog.wizer.fr/2013/11/angularjs-facebook-with-a-django-rest-api/

**Comment by litstrong** [comment]
https://yeti.co/blog/oauth2-with-django-rest-framework/

**Comment by picodoth** [comment]
I was watching the parse tutorial last night.

**Comment by litstrong** [comment]
oauth
client side v.s. server side:
https://github.com/oauth-io/oauthd/wiki/Understanding-client-side-flow-and-server-side-flow

**Comment by litstrong** [comment]
client side demo:
https://yeti.co/blog/social-auth-with-django-rest-framework/

**Comment by litstrong** [comment]
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

However, if you need to implement browser-based login for an app without using our SDKs, such as in a webview for a native desktop app (for example Windows 8), or a login flow using entirely server-side code, you can build a Login flow for yourself by using browser redirects. This guide will take you through each step of the login flow and show you how to implement each one without using our SDKs:

**Comment by litstrong** [comment]
todos:
- automatically create user
- generate our token

**Comment by litstrong** [comment]
Authentication in rest framework:
http://www.django-rest-framework.org/api-guide/authentication/

**Comment by litstrong** [comment]
The default TokenAuthentication class does not support periodically changed, however you can extend it to achieve this functionality.

http://stackoverflow.com/questions/14567586/token-authentication-for-restful-api-should-the-token-be-periodically-changed

**Comment by litstrong** [comment]
Finally, we plan to use following solutions:

**Login:**
Server side: #13
Client side: #21

**Logout:**
Invalid token in the client.
