### ISSUE TITLE
Make a basic login UI and trying to integrate with parse

### ISSUE THREAD

**Issue by picodoth** [litstrong/bope#11]

**Comment by picodoth** [comment]
basic ui with traditional login form is taken care of by https://github.com/litstrong/bope/commit/1c043513487d46a7387b48d9f853892f198b5831, however, in reality we just want a fb/wechat login channel. This will be done after BE is ready to be tested.

**Comment by picodoth** [comment]
create https://github.com/litstrong/bope/issues/15 to further address this problem.

**Comment by litstrong** [comment]
This issue was moved to litstrong/pentsh#11
