### ISSUE TITLE
Fix client slow issue when clicking tab button

### ISSUE THREAD

**Issue by litstrong** [litstrong/bope#125]

**Comment by picodoth** [comment]
working on this one

**Comment by picodoth** [comment]
Observations: 
1. ComponentDidMount inside event-item.js is seriously affecting the tab switching performance.
What needs to be fixed: return avar_url directly for anything related with user including created_by, enrollment_set, punch_set. This needs a backend case to fix.
2. TouchableHighlight wrapper is also affecting performance:
What needs to be fixed: Use TouchableWithoutFeedback over TouchableHighlight. This can be done within the case.
3. Not all iphones have same tab switching speed. IPhone 6+ with ios@9.3.2 (junbin's iphone) seems like much slower than shaoyang and han's iphone. All tested through the installation version from hockapp.

**Comment by picodoth** [comment]
will leave this case open till #126 got fixed, and client side need to make change accordingly.

**Comment by litstrong** [comment]
The 3rd reason seams so wried, we'll have more tests to check on that.

**Comment by litstrong** [comment]
This issue was moved to litstrong/pentsh#7
