### ISSUE TITLE
React Image with remote source doesn't work

### ISSUE THREAD

**Issue by litstrong** [litstrong/bope#53]
```
<Image source={{ uri: 'http://facebook.github.io/react/img/logo_og.png' }} />
```

Doesn't show out the image.

**Comment by litstrong** [comment]
https://facebook.github.io/react-native/docs/images.html

Many of the images you will display in your app will not be available at compile time, or you will want to load some dynamically to keep the binary size down. Unlike with static resources, `you will need to manually specify the dimensions of your image`.

```
// GOOD
<Image source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}}
       style={{width: 400, height: 400}} />

// BAD
<Image source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}} />
```

**Comment by picodoth** [comment]
Shall we close this?

**Comment by litstrong** [comment]
Yes. Closed.
