### ISSUE TITLE
Fix snapshot test

### ISSUE THREAD

**Issue by picodoth** [litstrong/bope#92]
Known issue:
1. mvp/client/bopepob/node_modules/react-native-material-kit/lib/mdl/index.js
line 9, need to rename Spinner.js to Spinner.ios.js
to resolve 'Spinner' module cannot be found error
2. mvp/client/bopepob/node_modules/react-native-router-flux/src/NavBar.js
line 154, need to comment out propTypes declaration block and line 475 propType assinment to resolve propType of undefined error

We have to manually fix this problems now. We need to resolve this for real.

**Comment by litstrong** [comment]
This issue was moved to litstrong/pentsh#14
